### PR TITLE
Warmup

### PR DESCRIPTION
**Pull request by spot88**
Points don't count if in warmup mode. Needs testing... Seems to work with me.

### CODE REVIEW

**Comment by rogeraabbccdd** [comment]
I think a cvar to enable or disable this is better.

**Comment by spot88** [comment]
Do you have time to add this "now"? or?

**Comment by rogeraabbccdd** [comment]
Maybe weekend.
I have 2 exams this week.

**Comment by rogeraabbccdd** [comment]
Feature added in 3.0.3.Kento.17.

**Pull request closed without merging**
